### PR TITLE
Ensure attrs exist before going further

### PR DESCRIPTION
**Pull request by kenips**
Fixes popcal not closing when you use Esc key or click outside of it.

### CODE REVIEW

**Comment by jacojoubert** [comment]
Thanks!

**Comment by kenips** [comment]
Hey @jacojoubert mind pumping out a 0.7.2 if nothing is expected to merge soon?

**Comment by zachaysan** [comment]
@kenips Jaco's out of town until Wednesday. He's [photographing bears](https://imgur.com/mYqwCbt).

**Comment by kenips** [comment]
haha awesome! Algonquin?

No rush - whenever you guys have time. Just easier to use main npm.

**Comment by zachaysan** [comment]
BC actually. We've missed him greatly. Are you going to be at that Ember thing Unspace is putting on in September?

**Comment by kenips** [comment]
Nice! I won't be able to make it. @artsyca will be there!

**Comment by jacojoubert** [comment]
@kenips 0.7.2 has been published.

**Comment by kenips** [comment]
Awesome. Thanks man, welcome back!

**Pull request merged**
