### PR TITLE
Add all exports to dist.

### LINKED ISSUE #91: Not all modules are being exported in named amd?
Steps to reproduce:

Using the named-amd build in ember-cli, attempting to import `EuiButtonTemplate`:

  `import { EuiButtonComponent, EuiButtonTemplate } from 'emberui'`

This is necessary for registering with the container during testing. However, `EuiButtonTemplate` is always undefined.

Looking at the dist, around line [1421](https://github.com/emberui/emberui/blob/master/dist/named-amd/emberui.js#L1421), it seems that many items are being imported, but not all are being included in the `__exports__`

Just opening this issue to confirm that the intention is that all modules are exported?

### PR DESCRIPTION
**Pull request by artsyca**
Fixes #91

### CODE REVIEW

**Comment by elucid** [comment]
Looks good *but* could you push a version without the corresponding dist changes? We typically only update dist when we cut a new version. Once this is merged I will cut a new version and those changes will be brought back.

**Comment by artsyca** [comment]
Sure! Makes total sense. Pushing now.

**Comment by artsyca** [comment]
@elucid: please see the updated commit!

**Comment by elucid** [comment]
Hey @artsyca, @ghedamat cut 0.4.2 which includes this a couple hours ago.

Thanks for the PR.

**Pull request merged**
