### PR TITLE
[WIP] Ember addon dist

### PR DESCRIPTION
**Pull request by ghedamat**
still a work in progress

Partially based on the work done in https://github.com/emberui/emberui/tree/ember-addon but the idea is to take a simpler approach that includes the `dist` version directly, as done by @artsyca in https://github.com/rebaselabs/ember-cli-emberui

* [x] add font awesome to bower.json and to addon brocfile 
* [x] add conditional include for default theme (as per other addon branch) and include basic css
* [ ] add generator for custom theme 
* [ ] add logic to deploy script 
* [ ] initializer problem 

(see #85)

### CODE REVIEW

**Comment by ghedamat** [comment]
@elucid @hhff I clearly didn't have much time to look at this,

it is pretty much done aside from the fonts issue

I'd love some testing/feedback if you're up for it

(npm-link and bower-link are what I used to test this into a new ember-cli project)

**Comment by hhff** [comment]
@ghedamat amazing work.  will test asap!

**Comment by jacojoubert** [comment]
What needs to be done on the fonts? I can drop Font Awesome and switch to a custom built font so it is smaller and eliminates a dependency.

**Comment by elucid** [comment]
^ @jacojoubert that is what needs to be done

**Comment by jacojoubert** [comment]
Ok will see if I can squeeze in the font work this week.

**Comment by jacojoubert** [comment]
Thanks for your help here @ghedamat , but I think it is best is we give up on our own build process and move over to ember-cli. I have started work here: #96

**Pull request closed without merging**
